---
all:
  hosts:
  children:
    app:
      hosts:
        vm2:
          ansible_host: 51.250.12.210 
        vm3:
          ansible_host: 51.250.68.244 
    web:
      hosts:
        vm1:
          ansible_host: 130.193.39.32 
    database:
      vars:
        pg_ver: 14
        pg_data: /data/pgsql
      hosts:
        vm1:
          ansible_host: 130.193.39.32 
