---
all:
  vars:
    ansible_python_interpreter = /usr/bin/python3
    ansible_user = ubuntu
    ansible_ssh_private_key_file = ~/.ssh/id_rsa
  hosts:
  children:
    app:
      hosts:
        vm2:
          ansible_host: 192.168.15.6
        vm3:
          ansible_host: 192.168.15.10
          ansible_user: cloud-user
          
    web:
      hosts:
        vm1:
          ansible_host: 192.168.15.13
    database:
      vars:
        pg_ver: 14
        pg_data: /data/pgsql
      hosts:
        vm1:
          ansible_host: 192.168.15.13

 